version: '2'
services:
  application:
    build: docker/application
    networks:
      - app_net
    volumes:
      - ./:/var/www

  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - application
    networks:
      - app_net
    volumes:
      - ./docker/nginx/symfony3.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - application

networks:
  app_net:
    driver: bridge
